const db = require('../db/database');

const seedData = {
  flashcard_decks: [
    { id: 1, name: 'Psychopathology Basics', description: 'Core concepts in clinical psychology', category: 'psychopathology' },
    { id: 2, name: 'Therapeutic Approaches', description: 'Major therapy modalities', category: 'therapy' },
    { id: 3, name: 'Assessment & Diagnosis', description: 'Clinical assessment tools and criteria', category: 'assessment' },
  ],
  flashcards: [
    { deck_id: 1, front: 'What is transference?', back: 'The unconscious redirection of feelings from one person to another, often originating in early significant relationships. The client projects feelings about a past figure onto the therapist.', difficulty: 'medium' },
    { deck_id: 1, front: 'What is the difference between sadness and depression?', back: 'Sadness is a normal emotional response to loss or disappointment that passes with time. Depression is a clinical condition involving persistent low mood (2+ weeks), loss of interest, sleep/ppetite changes, cognitive impairment, and functional impairment.', difficulty: 'medium' },
    { deck_id: 1, front: 'What are the core symptoms of Generalized Anxiety Disorder (GAD)?', back: 'Excessive, difficult-to-control worry occurring more days than not for 6+ months, accompanied by at least 3 of: restlessness, fatigue, concentration difficulty, irritability, muscle tension, sleep disturbance.', difficulty: 'hard' },
    { deck_id: 1, front: 'What is catastrophizing?', back: 'A cognitive distortion where one expects the worst possible outcome. The mind jumps to catastrophic conclusions with minimal or no evidence. Common in anxiety disorders.', difficulty: 'easy' },
    { deck_id: 1, front: 'What is the diathesis-stress model?', back: 'A framework explaining mental illness as the result of an interaction between a predisposition (diathesis - genetic, biological, psychological) and environmental stress (life events, trauma).', difficulty: 'medium' },
    { deck_id: 1, front: 'What is rumination?', back: 'Repetitive, passive dwelling on negative thoughts, causes, and consequences of distress. Unlike problem-solving, it does not lead to resolution and is a key feature of depression.', difficulty: 'easy' },
    { deck_id: 1, front: 'What is emotional dysregulation?', back: 'Difficulty in managing, modulating, or responding appropriately to emotional experiences. May involve intense emotional reactions, slow return to baseline, or inability to use coping strategies effectively.', difficulty: 'medium' },

    { deck_id: 2, front: 'What is unconditional positive regard?', back: 'A core condition in person-centered therapy (Rogers). The therapist accepts and supports the client without judgment, regardless of what the client says or does.', difficulty: 'easy' },
    { deck_id: 2, front: 'What is cognitive restructuring?', back: 'A CBT technique involving identification, evaluation, and modification of maladaptive thought patterns. The client learns to challenge automatic thoughts and replace them with balanced alternatives.', difficulty: 'medium' },
    { deck_id: 2, front: 'What is the difference between CBT and DBT?', back: 'CBT focuses on identifying and changing thought patterns. DBT (a form of CBT) adds mindfulness, distress tolerance, emotion regulation, and interpersonal effectiveness skills. DBT was designed for borderline personality disorder.', difficulty: 'hard' },
    { deck_id: 2, front: 'What is motivational interviewing?', back: 'A collaborative, person-centered counseling approach designed to strengthen motivation for change by exploring and resolving ambivalence. Uses OARS: Open questions, Affirmations, Reflections, Summaries.', difficulty: 'medium' },
    { deck_id: 2, front: 'What is exposure therapy?', back: 'A behavioral technique where the client is gradually and repeatedly exposed to feared stimuli in a safe context, reducing avoidance and anxiety response over time. Used for phobias, PTSD, OCD.', difficulty: 'medium' },
    
    { deck_id: 3, front: 'What does the GAD-7 measure?', back: 'Generalized Anxiety Disorder 7-item scale. A brief self-report tool screening for anxiety severity over the past 2 weeks. Scores: 0-4 minimal, 5-9 mild, 10-14 moderate, 15-21 severe.', difficulty: 'easy' },
    { deck_id: 3, front: 'What are the DSM-5 criteria for a major depressive episode?', back: '5+ of the following for 2+ weeks (at least one must be depressed mood or anhedonia): depressed mood, diminished interest, weight change, sleep histurbance, stile changes, psychomotor changes, fatigue, worthlessness/guilt.concentration difficulty, recurrent thoughts of death.', difficulty: 'hard' },
    { deck_id: 3, front: 'What is a mental status examination (MSE)?', back: 'A structured assessment of a client\\'s current mental state, covering: appearance, behavior, speech, mood, affect, thought process, thought content, perception, cognition, insight, judgment.', difficulty: 'medium' },
    { deck_id: 3, front: 'What is the PHQ-9?', back: 'Patient Health Questionnaire 9-item. A self-report tool screening for depression severity over the past 2 weeks. Scores: 0-4 minimal, 5-9 mild, 10-14 moderate, 15-19 moderately severe,20-27 severe.', difficulty: 'easy' },
  ],
  case_scenarios: [
    { id: 1, title: 'Persistent Low Mood', client_profile: '24-year-old graduate student', presenting_concern: 'Persistent low mood, loss of interest in previously enjoyed activities, difficulty concentrating, and disrupted sleep hi\İ\›œÈİ™\ˆH\İÚ^ÙYZÜËˆ™\ÜÈ[˜Ü™X\ÙYXØY[ZXÈİ™\ÜË‰ËY™šXİ[Nˆ	Ú[\›YYX]IËØ]YÛÜNˆ	Û[ÛÙ	ÈKˆÈYˆ‹]Nˆ	Ô™Xİ\œ™[[šXÈ]XÚÜÉËÛY[Ü›Ùš[Nˆ	ÌÍK^YX\‹[ÛÛÙØ\™H›Ù™\ÜÚ[Û˜[	Ë™\Ù[[™×ØÛÛ˜Ù\›ˆ	Ô™Xİ\œ™[[šXÈ]XÚÜÈÚ][]][ÛœËÚÜ™\ÜÈÙˆœ™X][™™X\ˆÙˆÜÚ[™ÈÛÛ›Ûˆ\Èİ\Y]›ÚY[™ÈX›XÈ˜[œÜÜ[™Ü›İÙYXÙ\ËˆŞ[\Û\ÈÛÜœÙ[š[™Èİ™\ˆÈ[ÛË‰ËY™šXİ[Nˆ	Ú[\›YYX]IËØ]YÛÜNˆ	Ø[Y]IÈKˆÈYˆË]Nˆ	Õ˜][XHY\ˆXØÚY[	ËÛY[Ü›Ùš[Nˆ	Ì^YX\‹[ÛXXÚ\‰Ë™\Ù[[™×ØÛÛ˜Ù\›ˆ	Ò[\Ú]™HY[[ÜšY\ËšYÚX\™\Ë[™\\šYÚ[[˜ÙH›ÛİÚ[™ÈHÙ\š[İ\ÈØ\ˆXØÚY[[ÛÈYÛËˆ]›ÚYÈš]š[™È[™™XÛÛY\È\İ™\ÜÙY™X\ˆ˜Y™šXËˆY™šXİ[HÛY\[™È[™ÛÛ˜Ù[˜][™È]ÛÜšË‰ËY™šXİ[Nˆ	ØY˜[˜ÙY	ËØ]YÛÜNˆ	İ˜][XIÈKˆÈYˆ]Nˆ	ĞÚ[ÛÙ˜][XH[™™[][ÛœÚ\ÉËÛY[Ü›Ùš[Nˆ	ÌÌK^YX\‹[ÛX\šÙ][™È^Xİ]]™IË™\Ù[[™×ØÛÛ˜Ù\›ˆ	Ô]\›ˆÙˆ[œİX›H™[][ÛœÚ\Ë[[œÙH™X\ˆÙˆX˜[™Û›Y[[[İ[Û˜[İÚ[™ÜË[™[\[Ú]™H™Z]š[Ü‹ˆ™\ÜÈ\İÜHÙˆÚ[ÛÙ[[İ[Û˜[™YÛXİˆÛÛY][Y\È™Y[Èˆ™[\W‹‰ËY™šXİ[Nˆ	ØY˜[˜ÙY	ËØ]YÛÜNˆ	Ü\œÛÛ˜[]IÈKˆÈYˆK]Nˆ	ÔİY[Ú]^[H[Y]IËÛY[Ü›Ùš[Nˆ	ÌŒ^YX\‹[Û[™\™Ü˜YX]HİY[	Ë™\Ù[[™×ØÛÛ˜Ù\›ˆ	Ñ^Ù\ÜÚ]™HÛÜœHX›İ]^[\ÈXY[™ÈÈ›ØÜ˜\İ[˜][Û‹ÛY\\İ\˜˜[˜ÙK[™\ÚXØ[Ş[\Û\È
XYXÚ\ËİÛXXÚ\ÜİY\ÊKˆ™\ÜÈ™Y[[™Èˆ™œ›Ş™[—ˆˆ\š[™ÈİYHÙ\ÜÚ[ÛœË‰ËY™šXİ[Nˆ	Ø™YÚ[›™\‰ËØ]YÛÜNˆ	Ø[Y]IÈKˆKˆÜØÙWÜ]Y\İ[ÛœÎˆÂˆÈYˆKØÙ[˜\š[Îˆ	ĞHK^YX\‹[ÛÛY[™\Ù[ÈÚ]\œÚ\İ[ØY™\ÜËÜÜÈÙˆ[\™\İ[ˆXİ]š]Y\ËX\›H[Ü›š[™È]ØZÙ[š[™Ë[™ÚYÛšYšXØ[ÙZYÚÜÜÈİ™\ˆH\İˆ[ÛË‰Ë]Y\İ[Ûˆ	ÕÚ]\È[İ\ˆY™™\™[X[XYÛ›ÜÚ\È[™Ú]\\ˆ[™›Ü›X][ÛˆÛİ[[İHØ]\ÉË[Ù[Ø[œİÙ\ˆ	ĞÛÛœÚY\ˆXZ›Üˆ\™\ÜÚ]™H\ÛÜ™\‹Y\İY[\ÛÜ™\‹š\Û\ˆ\™\ÜÚ[Û‹ÜˆYYXØ[Ø]\Ù\È
\İ\›ÚY\ÛK[™[ZXJKˆ\ÜÙ\ÜÈİZXÚYHš\ÚË™]š[İ\È\\ÛÙ\Ë˜[Z[H\İÜKİXœİ[˜ÙH\ÙK[™ŞXÚÜÛØÚX[İ™\ÜÛÜœË‰ËØ]YÛÜNˆ	Û[ÛÙ	ËY™šXİ[Nˆ	ÛYY][IÈKˆÈYˆ‹ØÙ[˜\š[Îˆ	ĞHNK^YX\‹[ÛÛÛYÙHİY[\Èœ›İYÚHœšY[™ÈY\ˆ^™\ÜÚ[™ÈİYÚÈ]‰Ü[ÜH\™HØ]Ú[™×‰È[H[™X\š[™È›ÚXÙ\ÈÛÛ[Y[[™ÈÛˆZ\ˆ™Z]š[Ü‹‰Ë]Y\İ[Ûˆ	ÕÚ]\È[İ\ˆ[[YYX]H\ÜÙ\ÜÛY[[™X[˜YÙ[Y[[ÉË[Ù[Ø[œİÙ\ˆ	Ğ\ÜÙ\ÜÈØY™]K˜]\™HÙˆŞXÚİXÈŞ[\Û\Ë\˜][Û‹İXœİ[˜ÙH\ÙK[™š\ÚÈÈÙ[‹Ûİ\œËˆ[Hİ]İXœİ[˜ÙKZ[™XÙYŞXÚÜÚ\ËˆÛÛœÚY\ˆ™Y™\œ˜[ÈŞXÚX]KˆÈ›İ˜[Y]HÜˆ\ÛZ\ÜÈH^\šY[˜Ù\Ë‰ËØ]YÛÜNˆ	ÜŞXÚÜÚ\ÉËY™šXİ[Nˆ	Ú\™	ÈKˆÈYˆËØÙ[˜\š[Îˆ	ĞHÍK^YX\‹[Û™\Ù[ÈÚ]™Xİ\œ™[[šXÈ]XÚÜË]›ÚY[˜ÙHÙˆX›XÈÜXÙ\Ë[™ÚYÛšYšXØ[\İ™\ÜÈY™™Xİ[™ÈZ[H[˜İ[Ûš[™È›ÜˆÈ[ÛË‰Ë]Y\İ[Ûˆ	ÕÚ]Ûİ[[İHÈ™^ÉË[Ù[Ø[œİÙ\ˆ	ĞÛÛ™XİÜ›İYÚ\ÜÙ\ÜÛY[[˜ÛY[™ÈÛœÙ]šYÙÙ\œË]›ÚY[˜ÙH]\›œËİXœİ[˜ÙH\ÙK[™YYXØ[[K[İ]È
Ø\™XXË\›ÚY
Kˆ\ÜÙ\ÜÈ›ÜˆYÛÜ˜\ØšXKˆÛÛœÚY\ˆĞ•Ú]^Üİ\™KŞXÚÙYXØ][Û‹[™ÜÜÚX›HÔÔ’\Ë‰ËØ]YÛÜNˆ	Ø[Y]IËY™šXİ[Nˆ	ÛYY][IÈKˆÈYˆØÙ[˜\š[Îˆ	ĞH^YX\‹[ÛÛY[™\ÜÈH‹[[Û\İÜHÙˆš[™ÙHX][™È\\ÛÙ\È›ÛİÙYHÙ[‹Z[™XÙY›ÛZ][™ËØØİ\œš[™ÈËM[Y\È\ˆÙYZË‰Ë]Y\İ[Ûˆ	ÕÚ]\È[İ\ˆ\ÜÙ\ÜÛY[\›ØXÚ[™Ú]Ûİ[[İH^Ü™OÉË[Ù[Ø[œİÙ\ˆ	Ğ\ÜÙ\ÜÈ›Üˆ[[ZXH™\›ÜØNˆœ™\]Y[˜ŞKÙ\˜][ÛˆÙˆš[™Ù\ËÛÛ\[œØ]ÜH™Z]š[ÜœË›ÙH[XYÙHÛÛ˜Ù\›œË[Xİ›Û]H\ÜİY\Ë[[\›ÜÚ[Û‹ˆ^Ü™HÙZYÚ\İÜKšYÙÙ\œËÛË[[Ü˜šY\™\ÜÚ[Û‹Ø[Y]K[™\ÜÙ\ÜÈİZXÚYHš\ÚË‰ËØ]YÛÜNˆ	ÙX][™ÉËY™šXİ[Nˆ	Ú\™	ÈKˆÈYˆKØÙ[˜\š[Îˆ	ĞHL^YX\‹[ÛÛY[™\ÜÈY™šXİ[HÛY\[™È›ÜˆÈ[ÛÈ8 %ZÙ\Èˆİ\œÈÈ˜[\ÛY\ØZÙ\È]ÈSH[™Ø[››İ™]\›ˆÈÛY\‰Ë]Y\İ[Ûˆ	ÒİÈÛİ[[İH\ÜÙ\ÜÈ[™›Ü›][]H[ˆ[\™[[ÛÉË[Ù[Ø[œİÙ\ˆ	Ğ\ÜÙ\ÜÈÛY\YÚY[™KØY™™Z[™KØ[ÛÚÛ[ZÙKØÜ™Y[ˆ[YKİ™\ÜÛÜœË[ÛÙ[™YYXØ[ÛÛ™][ÛœËˆÛÛœÚY\ˆĞ•RKÛY\™\İšXİ[Ûˆ\˜\Kİ[][\ÈÛÛ›Ûˆ[Hİ]\™\ÜÚ[Û‹[Y]KÛY\\™XK‰ËØ]YÛÜNˆ	ÜÛY\	ËY™šXİ[Nˆ	ÛYY][IÈKˆÈYˆ‹ØÙ[˜\š[Îˆ	ĞHM‹^YX\‹[Û\Èœ›İYÚH\™[ÈYHÈXÛ[š[™ÈÜ˜Y\ËÛØÚX[Ú]˜]Ø[[™\œš]Xš[]Hİ™\ˆH\İ[ÛË‰Ë]Y\İ[Ûˆ	ÕÚ]\È[İ\ˆY™™\™[X[[™\ÜÙ\ÜÛY[[ÉË[Ù[Ø[œİÙ\ˆ	ĞÛÛœÚY\ˆ\™\ÜÚ[Û‹ÛØÚX[[Y]K[Z[™ËİXœİ[˜ÙH\ÙKÜˆ[Y\™Ú[™ÈŞXÚÜÚ\Ëˆ[™ØYÙH›İYÛ\ØÙ[
[Û™JH[™\™[Ëˆ\ÜÙ\ÜÈ[ÛÙİZXÚYHš\ÚËY\ˆ™[][ÛœÚ\ËXØY[ZXÈİ™\ÜË˜[Z[H[˜[ZXÜË[™ØÜ™Y[ˆ›ÜˆİXœİ[˜ÙH\ÙK‰ËØ]YÛÜNˆ	ØYÛ\ØÙ[	ËY™šXİ[Nˆ	ÛYY][IÈKˆÈYˆËØÙ[˜\š[Îˆ	ĞH^YX\‹[ÛÛY[\ØÜšX™\ÈH]\›ˆÙˆ[[œÙK[œİX›H™[][ÛœÚ\Ë™X\ˆÙˆX˜[™Û›Y[[™[[İ[Û˜[İÚ[™ÜÈİ™\ˆÙ]™\˜[YX\œË‰Ë]Y\İ[Ûˆ	ÕÚ]™X]\™\ÈÛİ[[İH\ÜÙ\ÜÈ[™Ú]\›ØXÚÛİ[[İHZÙOÉË[Ù[Ø[œİÙ\ˆ	Ğ\ÜÙ\ÜÈ›Üˆ›Ü™\›[™H\œÛÛ˜[]H\ÛÜ™\ˆ[[İ[Û˜[\Ü™Yİ[][Û‹Y[]H\İ\˜˜[˜ÙK[\[Ú]š]KÙ[‹Z\›H\İÜKÚ›ÛšXÈ[\[™\ÜËˆ\ÙHH˜[Y][™È\›ØXÚˆÛÛœÚY\ˆ•™Y™\œ˜[ˆ\ÜÙ\ÜÈİZXÚYKÜÙ[‹Z\›Hš\ÚÈØ\™Y[K‰ËØ]YÛÜNˆ	Ü\œÛÛ˜[]IËY™šXİ[Nˆ	Ú\™	ÈKˆÈYˆØÙ[˜\š[Îˆ	ĞHMK^YX\‹[Û™\ÜÈÜ˜YX[ÛœÙ]ÙˆY[[ÜHY™šXİ[Y\ËÙ][™ÈÜİ[ˆ˜[Z[X\ˆXÙ\Ë[™\œÛÛ˜[]HÚ[™Ù\Èİ™\ˆ[ÛË‰Ë]Y\İ[Ûˆ	ÕÚ]\È[İ\ˆ\ÜÙ\ÜÛY[\›ØXÚÉË[Ù[Ø[œİÙ\ˆ	ĞÛÛœÚY\ˆ™]\›ØÛÙÛš]]™H\ÛÜ™\‹ˆÛÛ™XİÛÙÛš]]™H\ÜÙ\ÜÛY[
STÑKÓ[ĞĞJK[Hİ]™]™\œÚX›HØ]\Ù\È
ŒL‹\›ÚY\™\ÜÚ[ÛŠK™]\›Ú[XYÚ[™È™Y™\œ˜[\ÜÙ\ÜÈ[˜İ[Û˜[[\Z\›Y[ØY™]H
š]š[™ËÛÛÚÚ[™ÊK[™˜[Z[Hİ\Ü‰ËØ]YÛÜNˆ	Û™]\›ØÛÙÛš]]™IËY™šXİ[Nˆ	Ú\™	ÈKˆKˆÚÚ[×ÜØÙ[˜\š[ÜÎˆÂˆÈYˆKÚÚ[Û˜[YNˆ	ĞXİ]™H\İ[š[™ÉËØÙ[˜\š[×İ^ˆ	Ó›Ø›ÙH™X[H[™\œİ[™ÈYK‰ËÛÜœ™XİÜ™\ÜÛœÙNˆ	Ò]Ûİ[™ÈZÙH[İW	İ™H™Y[ˆ™Y[[™È[™\œİÛÙˆØ[ˆ[İH[YH[Ü™HX›İ]Ú]]	ÜÈ™Y[ˆZÙOÉË^[˜][Ûˆ	Õ\È™\ÜÛœÙH™Y›XİÈ˜XÚÈÚ]HÛY[ØZYÚ]İ]YÛY[ˆ]˜[Y]\ÈZ\ˆ^\šY[˜ÙH[™ÚİÜÈ[İW	Ü™H\İ[š[™ÈHÚXÚZ[È\İ[™Ü[œÈÜXÙH›Üˆ[HÈÚ\™H[Ü™K‰ÈKˆÈYˆ‹ÚÚ[Û˜[YNˆ	Ñ[\]XÈ™Y›Xİ[Û‰ËØÙ[˜\š[×İ^ˆ	ÒH\İ™Y[ÛÈÜİˆ]™\][™ÈHHÈÈÛÙ\ÈÜ›Û™Ë‰ËÛÜœ™XİÜ™\ÜÛœÙNˆ	Ò]Ûİ[™ÈZÙH[İW	Ü™H™Y[[™È™X[HİXÚÈ[™\ØÛİ\˜YÙYšYÚ›İËˆ]]\İ™H[˜Ü™YX›Hœ\İ˜][™Ë‰Ë^[˜][Ûˆ	Õ\È™Y›XİÈ›İHÛÛ[
™Y[[™ÈİXÚÊH[™H[[İ[Ûˆ
\ØÛİ\˜YÙYœ\İ˜]Y
Kˆ]ÚİÜÈ[İ—	Ü™H˜XÚÚ[™È›İ\İÚ]HÛY[Ø^\Ë]Ú]^W	Ü™H™Y[[™Ë‰ÈKˆÈYˆËÚÚ[Û˜[YNˆ	ÓÜ[‹Q[™Y]Y\İ[ÛœÉËØÙ[˜\š[×İ^ˆ	ÒHÛ—	İÛ›İÈYˆHØ[ÈÙY\ÛÚ[™ÈÈ\˜\K‰ËÛÜœ™XİÜ™\ÜÛœÙNˆ	ÕÚ]\È]X›İ]\˜\H]	ÜÈXZÚ[™È[İH™Y[[˜Ù\Z[ÉË^[˜][Ûˆ	Õ\È\È[ˆÜ[ˆ]Y\İ[Ûˆ][š]\ÈHÛY[È^Ü™HZ\ˆ™Y[[™ÜÈ˜]\ˆ[ˆÚ]š[™ÈHY\ËÛ›È[œİÙ\‹ˆ]ÚİÜÈİ\š[ÜÚ]HÚ]İ]™Z[™ÈÛÛ™œ›Û][Û˜[‰ÈKˆÈYˆÚÚ[Û˜[YNˆ	Õ˜[Y][™ÉËØÙ[˜\š[×İ^ˆ	ÒHÛ›İÈHÚİ[—	İ™H\È\Ù]İ™\ˆÛÛY][™ÈÛÈÛX[]H\İØ[—	İ[]‰ËÛÜœ™XİÜ™\ÜÛœÙNˆ	ÕÚ][İW	Ü™H™Y[[™ÈXZÙ\ÈÙ[œÙKˆ]™[ˆ[™ÜÈ]ÙY[HÛX[Ø[ˆØ\œHHİÙˆÙZYÚˆ\™W	ÜÈ›È‰ÜÚİ[ˆX›İ]İÈ[İH™Y[‰Ë^[˜][Ûˆ	Õ\È˜[Y]\ÈHÛY[	ÜÈ[[İ[Û˜[^\šY[˜ÙHÚ]İ]\ÛZ\ÜÚ[™ÈÜˆZ[š[Z^š[™È]ˆ][ÛÈÙ[HÚ[[™Ù\ÈHÙ[‹XÜš]XÚ\ÛH
ˆœÚİ[—	İ™H\Ù]ˆŠK‰ÈKˆÈYˆKÚÚ[Û˜[YNˆ	Ôİ[[X\š^š[™ÉËØÙ[˜\š[×İ^ˆ	ÔÛÈš\œİ^H›ÜÜÈÜš]XÚ^™YYK[ˆ^HœšY[™Ø[˜Ù[Y[œË[™›İÈHØ[—	İÛY\ˆ]™\][™È™Y[ÈZÙH]	ÜÈ˜[[™È\\‰ËÛÜœ™XİÜ™\ÜÛœÙNˆ	ÔÛÈ]Ûİ[™ÈZÙH[İW	İ™HYÙ]™\˜[Y™šXİ[[™ÜÈ\[ˆ[ˆH›İÈKHÜš]XÚ\ÛH]ÛÜšËHØ[˜Ù[Y[‹[™›İÈ›İX›HÛY\[™Ëˆ[™][™Y[Èİ™\Ú[Z[™Ëˆ\È]šYÚÉË^[˜][Ûˆ	Õ\Èİ[[X\Hœš[™ÜÈÙÙ]\ˆHÙ^HÚ[ÈHÛY[Y[[Û™YÚİÜÈ[İ—	İ™H™Y[ˆ\İ[š[™Ë[™ÚXÚÜÈ[™\œİ[™[™Ëˆ][ÛÈ[ÈHÛY[ÙYHHšYÙÙ\ˆXİ\™K‰ÈKˆÈYˆ‹ÚÚ[Û˜[YNˆ	Ô™Yœ˜[Z[™ÉËØÙ[˜\š[×İ^ˆ	ÒH˜Z[Y[›İ\ˆ^[KˆW	ÛH\İ›İÛX\[›İYÚ›Üˆ\Ë‰ËÛÜœ™XİÜ™\ÜÛœÙNˆ	Ö[İW	Ü™HÛX\›H\Ø\Ú[YX›İ]H^[Kˆ]W	ÛHİ\š[İ\ÈKHÚ]Ûİ[]™HZÙHÈÛÚÈ]\È\ÈÛ™HY™šXİ[[ÛY[˜]\ˆ[ˆHİ][Y[X›İ][İ\ˆ[[YÙ[˜ÙOÉË^[˜][Ûˆ	Õ\ÈXÚÛ›İÛYÙ\ÈH™Y[[™Èš\œİ[ˆÙ[H[š]\ÈHÛY[ÈÛÛœÚY\ˆ[ˆ[\›˜]]™H\œÜXİ]™Kˆ]Ù\È›İ\ÛZ\ÜÈÜˆ\™İYHKH]Ü[œÈHÛÜ‹‰ÈKˆKŸNÂ‚™[˜İ[ÛˆÙYYY‘[\J
HÂˆÛÛœİXÚĞÛİ[H‹œ™\\™J	ÔÑSPÕÓÕS•

ŠH\ÈÛİ[”“ÓH›\ÚØ\™ÙXÚÜÉÊK™Ù]

K˜Ûİ[ÂˆYˆ
XÚĞÛİ[OOH
HÂˆÛÛœÛÛK›ÙÊ	ÈÙYY[™È]X˜\ÙK‹‹‰ÊNÂ‚ˆÛÛœİ[œÙ\XÚÈH‹œ™\\™J	ÒS”ÑT•S•È›\ÚØ\™ÙXÚÜÈ
Y˜[YK\ØÜš\[Û‹Ø]YÛÜJHSQTÈ
ËËËÊIÊNÂˆÙYY]K™›\ÚØ\™ÙXÚÜË™›Ü‘XXÚ
Oˆ[œÙ\XÚËœ[ŠšY›˜[YK™\ØÜš\[Û‹˜Ø]YÛÜJJNÂˆˆÛÛœİ[œÙ\Ø\™H‹œ™\\™J	ÒS”ÑT•S•È›\ÚØ\™È
XÚ×ÚYœ›Û˜XÚËY™šXİ[JHSQTÈ
ËËËÊIÊNÂˆÙYY]K™›\ÚØ\™Ë™›Ü‘XXÚ
ÈOˆ[œÙ\Ø\™œ[ŠË™XÚ×ÚYË™œ›ÛË˜˜XÚËË™Y™šXİ[JJNÂ‚ˆÛÛœİ[œÙ\Ø\ÙHH‹œ™\\™J	ÒS”ÑT•S•ÈØ\ÙWÜØÙ[˜\š[ÜÈ
Y]KÛY[Ü›Ùš[K™\Ù[[™×ØÛÛ˜Ù\›‹Y™šXİ[KØ]YÛÜJHSQTÈ
ËËËËËÊIÊNÂˆÙYY]K˜Ø\ÙWÜØÙ[˜\š[ÜË™›Ü‘XXÚ
ÈOˆ[œÙ\Ø\ÙKœ[ŠËšYË]KË˜ÛY[Ü›Ùš[KËœ™\Ù[[™×ØÛÛ˜Ù\›‹Ë™Y™šXİ[KË˜Ø]YÛÜJJNÂ‚ˆÛÛœİ[œÙ\ÜØÙHH‹œ™\\™J	ÒS”ÑT•S•ÈÜØÙWÜ]Y\İ[ÛœÈ
YØÙ[˜\š[Ë]Y\İ[Û‹[Ù[Ø[œİÙ\‹Ø]YÛÜKY™šXİ[JHSQTÈ
ËËËËËÊIÊNÂˆÙYY]K›ÜØÙWÜ]Y\İ[ÛœË™›Ü‘XXÚ
HOˆ[œÙ\ÜØÙKœ[ŠKšYKœØÙ[˜\š[ËKœ]Y\İ[Û‹K›[Ù[Ø[œİÙ\‹K˜Ø]YÛÜKK™Y™šXİ[JJNÂ‚ˆÛÛœİ[œÙ\ÚÚ[H‹œ™\\™J	ÒS”ÑT•S•ÈÚÚ[×ÜØÙ[˜\š[ÜÈ
YÚÚ[Û˜[YKØÙ[˜\š[×İ^ÛÜœ™XİÜ™\ÜÛœÙK^[˜][ÛŠHSQTÈ
ËËËËÊIÊNÂˆÙYY]KœÚÚ[×ÜØÙ[˜\š[ÜË™›Ü‘XXÚ
ÈOˆ[œÙ\ÚÚ[œ[ŠËšYËœÚÚ[Û˜[YKËœØÙ[˜\š[×İ^Ë˜ÛÜœ™XİÜ™\ÜÛœÙKË™^[˜][ÛŠJNÂ‚ˆÛÛœÛÛK›ÙÊ	È]X˜\ÙHÙYYYİXØÙ\ÜÙ[K‰ÊNÂˆBŸB‚›[Ù[K™^ÜÈHÈÙYYY‘[\KÙYY]HNÂ